"""UI Styles Package: Dark and Light stylesheets and design tokens."""
from .dark import MODERN_DARK_STYLESHEET
from .light import MODERN_LIGHT_STYLESHEET
from .tokens import (
    DARK_BG, DARK_CARD_BG, DARK_CARD_HOVER, DARK_BORDER, DARK_TEXT_PRIMARY, DARK_TEXT_SECONDARY,
    DARK_ACCENT_VOLTAGE, DARK_ACCENT_CURRENT, DARK_ACCENT_POWER, DARK_ACCENT_RESISTANCE,
    LIGHT_BG, LIGHT_CARD_BG, LIGHT_CARD_HOVER, LIGHT_BORDER, LIGHT_TEXT_PRIMARY, LIGHT_TEXT_SECONDARY,
    LIGHT_ACCENT_VOLTAGE, LIGHT_ACCENT_CURRENT, LIGHT_ACCENT_POWER, LIGHT_ACCENT_RESISTANCE,
    SCOPE_CH1_COLOR, SCOPE_CH2_COLOR, SCOPE_CH3_COLOR, SCOPE_CH4_COLOR, SCOPE_MATH_COLOR
)

__all__ = [
    "MODERN_DARK_STYLESHEET",
    "MODERN_LIGHT_STYLESHEET",
    "DARK_BG", "DARK_CARD_BG", "DARK_CARD_HOVER", "DARK_BORDER", "DARK_TEXT_PRIMARY", "DARK_TEXT_SECONDARY",
    "DARK_ACCENT_VOLTAGE", "DARK_ACCENT_CURRENT", "DARK_ACCENT_POWER", "DARK_ACCENT_RESISTANCE",
    "LIGHT_BG", "LIGHT_CARD_BG", "LIGHT_CARD_HOVER", "LIGHT_BORDER", "LIGHT_TEXT_PRIMARY", "LIGHT_TEXT_SECONDARY",
    "LIGHT_ACCENT_VOLTAGE", "LIGHT_ACCENT_CURRENT", "LIGHT_ACCENT_POWER", "LIGHT_ACCENT_RESISTANCE",
    "SCOPE_CH1_COLOR", "SCOPE_CH2_COLOR", "SCOPE_CH3_COLOR", "SCOPE_CH4_COLOR", "SCOPE_MATH_COLOR"
]
