"""UI Color and Typographic Tokens for Dark (Slate Control) and Light (Clean Laboratory) themes."""

# Dark Theme: "Slate Control"
DARK_BG = "#0F1117"
DARK_CARD_BG = "#1A1D24"
DARK_CARD_HOVER = "#262B33"
DARK_BORDER = "#2F3540"
DARK_TEXT_PRIMARY = "#E8EDF2"
DARK_TEXT_SECONDARY = "#8B95A5"

DARK_ACCENT_VOLTAGE = "#4A9BDB"
DARK_ACCENT_CURRENT = "#3FB58C"
DARK_ACCENT_POWER = "#D4A04A"
DARK_ACCENT_RESISTANCE = "#9B7FD4"

# Light Theme: "Clean Laboratory"
LIGHT_BG = "#F8FAFC"
LIGHT_CARD_BG = "#FFFFFF"
LIGHT_CARD_HOVER = "#F1F5F9"
LIGHT_BORDER = "#E2E8F0"
LIGHT_TEXT_PRIMARY = "#0F172A"
LIGHT_TEXT_SECONDARY = "#475569"

LIGHT_ACCENT_VOLTAGE = "#0284C7"
LIGHT_ACCENT_CURRENT = "#16A34A"
LIGHT_ACCENT_POWER = "#D97706"
LIGHT_ACCENT_RESISTANCE = "#9333EA"

# Oscilloscope Channel Trace Colors (Industry Standard Tek/Keysight/R&S)
SCOPE_CH1_COLOR = "#F59E0B"  # Amber / Yellow
SCOPE_CH2_COLOR = "#38BDF8"  # Cyan / Light Blue
SCOPE_CH3_COLOR = "#EC4899"  # Pink / Magenta
SCOPE_CH4_COLOR = "#10B981"  # Emerald Green
SCOPE_MATH_COLOR = "#A855F7" # Purple
SCOPE_GRID_DARK = "#262B33"
SCOPE_GRID_LIGHT = "#E2E8F0"
